---
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: SecurityGroup
metadata:
  name: sample-app-rds
  annotations:
    crossplane.io/external-name: raki-sample-org-production-sample-app-rds
spec:
  forProvider:
    groupName: raki-sample-org-production-sample-app-rds
    ingress:
      - fromPort: 5432
        toPort: 5432
        ipProtocol: tcp
        userIdGroupPairs:
          - description: Allow connections from EKS cluster security group
            groupId: sg-006111a78911238c0
    egress:
      - fromPort: -1
        toPort: -1
        ipProtocol: -1
        ipRanges:
          - description: Allow all egress traffic
            cidrIp: 0.0.0.0/0
---
apiVersion: database.aws.crossplane.io/v1beta1
kind: DBSubnetGroup
metadata:
  name: sample-app
  annotations:
    crossplane.io/external-name: raki-sample-org-production-sample-app
spec:
  forProvider:
    description: Subnet group for sample-app application (production environment)
    subnetIds:
      - subnet-061a9bac4d8523a42
      - subnet-0d56eb9abcb5355cf
      - subnet-077c55c98a67060e7
      - subnet-0391dd55f347f91e2
      - subnet-0f3ac66bf33851d27
      - subnet-0629b35560a0ad498
---
apiVersion: database.aws.crossplane.io/v1beta1
kind: RDSInstance
metadata:
  name: sample-app-postgres
  annotations:
    crossplane.io/external-name: raki-sample-org-production-sample-app-pg
