---
apiVersion: database.aws.crossplane.io/v1beta1
kind: DBSubnetGroup
metadata:
  name: sample-app
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  deletionPolicy: Delete
  forProvider:
    region: us-east-1
  publishConnectionDetailsTo:
    name: sample-app-postgres
